### ISSUE TITLE
GCC 4.1 compilation fix

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#364]
**Brian Nelson *<bignachos\@sf>* created a bug report on 2006-05-13 22:12:16 UTC**
*(Orig. from https://sourceforge.net/p/aspell/bugs/184)*

From http://bugs.debian.org/356444:

Your package fails to build with G++ 4.1.  I'm filing 
this bug as
important for now, but when 4.1 will be the default 
compiler in
unstable \(probably in a few weeks\) I'll upgrade this 
to serious.

A patch is below.

> Automatic build of aspell\_0.60.4-3 on bigsur by 
sbuild/mips 1.89
...
>  g++ -DHAVE\_CONFIG\_H -I. -I. -I./gen -I./gen 
-I./common -I./interfaces/cc/ 
-I./modules/speller/default/ 
-DLOCALEDIR=\"/usr/share/locale\" -g -Wall -O2 
-fno-exceptions -MT modules/filter/nroff.lo -MD -MP 
-MF modules/filter/.deps/nroff.Tpo -c 
modules/filter/nroff.cpp  -fPIC -DPIC -o 
modules/filter/.libs/nroff.o
> modules/filter/nroff.cpp:76: error: extra 
qualification '<unnamed>::NroffFilter::' on member 
'process\_char'
> modules/filter/nroff.cpp: In member function 
'bool<unnamed>::NroffFilter::ignore\_request\_argument\(\)':
> modules/filter/nroff.cpp:69: warning: comparison 
between signed and unsigned integer expressions
> make\[2\]: \*\*\* \[modules/filter/nroff.lo\] Error 1

\--- ./modules/filter/nroff.cpp~ 2006-03-12 
02:25:05.000000000 +0000
+++ ./modules/filter/nroff.cpp  2006-03-12 
02:25:09.000000000 +0000
@@ -73,7 +73,7 @@
return false;
\}

\-    bool NroffFilter::process\_char \(FilterChar::Chr 
c\);
\+    bool process\_char \(FilterChar::Chr c\);

public:
