### ISSUE TITLE
Patch: aspell-0.60.4 fails to compile with gcc-4.1

### ISSUE THREAD

**Issue by aspell-helper** [GNUAspell/aspell#344]
**Mark Loeser *<halcy0n\@sf>* created a patch on 2005-11-13 07:03:45 UTC**
*(Orig. from https://sourceforge.net/p/aspell/patches/127)*

modules/filter/nroff.cpp:76: error: extra qualification
'<unnamed>::NroffFilter::' on member 'process\_char'

You are specifying the scope of the member to be within
the class, inside of the class declaration.  The patch
removes this, which allows for it to compile.
